
 
#ifndef __OV2686_SENSOR_H
#define __OV2686_SENSOR_H


#define FULL_PERIOD_PIXEL_NUMS						1700
#define FULL_PERIOD_LINE_NUMS						1294
#define SVGA_PERIOD_PIXEL_NUMS						1708
#define SVGA_PERIOD_LINE_NUMS						644


#define IMAGE_SENSOR_SVGA_GRAB_PIXELS			5//0
#define IMAGE_SENSOR_SVGA_GRAB_LINES			5//1
#define IMAGE_SENSOR_FULL_GRAB_PIXELS			5//0
#define IMAGE_SENSOR_FULL_GRAB_LINES			5//1

#define IMAGE_SENSOR_SVGA_WIDTH					(800)
#define IMAGE_SENSOR_SVGA_HEIGHT					(600)
#define IMAGE_SENSOR_UXGA_WIDTH					(1600)
#define IMAGE_SENSOR_UXGA_HEIGHT					(1200)

#define IMAGE_SENSOR_PV_WIDTH					(IMAGE_SENSOR_SVGA_WIDTH - 8)
#define IMAGE_SENSOR_PV_HEIGHT					(IMAGE_SENSOR_SVGA_HEIGHT - 8)

#define IMAGE_SENSOR_FULL_WIDTH					(IMAGE_SENSOR_UXGA_WIDTH - 16)
#define IMAGE_SENSOR_FULL_HEIGHT					(IMAGE_SENSOR_UXGA_HEIGHT - 16)

#define OV2686_WRITE_ID							0x78
#define OV2686_READ_ID								0x79

typedef enum {
    SENSOR_MODE_INIT = 0,
    SENSOR_MODE_PREVIEW,
    SENSOR_MODE_CAPTURE,
    SENSOR_MODE_ZSD
} OV2686_SENSOR_MODE;

typedef enum
{
	OV2686_RGB_Gamma_m1 = 0,
	OV2686_RGB_Gamma_m2,
	OV2686_RGB_Gamma_m3,
	OV2686_RGB_Gamma_m4,
	OV2686_RGB_Gamma_m5,
	OV2686_RGB_Gamma_m6,
	OV2686_RGB_Gamma_night
}OV2686_GAMMA_TAG;

typedef enum
{
	CHT_806C_2 = 1,
	CHT_808C_2,
	LY_982A_H114,
	XY_046A,
	XY_0620,
	XY_078V,
	YG1001A_F
}OV2686_LENS_TAG;

UINT32 OV2686Open(void);
UINT32 OV2686Control(MSDK_SCENARIO_ID_ENUM ScenarioId, MSDK_SENSOR_EXPOSURE_WINDOW_STRUCT *pImageWindow, MSDK_SENSOR_CONFIG_STRUCT *pSensorConfigData);
UINT32 OV2686FeatureControl(MSDK_SENSOR_FEATURE_ENUM FeatureId, UINT8 *pFeaturePara,UINT32 *pFeatureParaLen);
UINT32 OV2686GetInfo(MSDK_SCENARIO_ID_ENUM ScenarioId, MSDK_SENSOR_INFO_STRUCT *pSensorInfo, MSDK_SENSOR_CONFIG_STRUCT *pSensorConfigData);
UINT32 OV2686GetResolution(MSDK_SENSOR_RESOLUTION_INFO_STRUCT *pSensorResolution);
UINT32 OV2686Close(void);

#endif /* __SENSOR_H */

